"""Database checks for Goyangi dedupe migrations. Uses only HANNI_TEST_DATABASE_URL."""
import os
import uuid
from pathlib import Path
import psycopg
import pytest
from psycopg_pool import ConnectionPool

from src.db import content_dedup

ROOT = Path(__file__).resolve().parents[1]
MIGRATION = (ROOT / 'migrations/table_updates42.sql').read_text()
MIGRATION_GUARD_FIX = (ROOT / 'migrations/table_updates43.sql').read_text()
MIGRATION_CONTENT_GUARD = (ROOT / 'migrations/table_updates44.sql').read_text()


@pytest.fixture
def db(monkeypatch):
    url = os.getenv('HANNI_TEST_DATABASE_URL')
    if not url:
        pytest.skip('Set HANNI_TEST_DATABASE_URL to an isolated local PostgreSQL database')
    host = psycopg.conninfo.conninfo_to_dict(url).get('host', '')
    assert host in ('localhost', '127.0.0.1') or host.startswith('/tmp/'), 'Local test DB only'
    schema = 'goyangi_dedup_' + uuid.uuid4().hex
    with psycopg.connect(url, autocommit=True) as conn:
        conn.execute(f'CREATE SCHEMA {schema}')
    pool = ConnectionPool(url, min_size=1, max_size=4, open=True,
                          kwargs={'options': f'-c search_path={schema}'})
    try:
        with pool.connection() as conn:
            conn.execute('''CREATE TABLE content_links (
                content_link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                role_id TEXT NOT NULL, url TEXT NOT NULL, uploaded_date TIMESTAMP,
                goyangi_content_id TEXT, goyangi_set_id TEXT,
                source_kind TEXT, source_message_id TEXT, root_message_id TEXT,
                original_url TEXT)''')
            conn.execute(MIGRATION)
            conn.execute(MIGRATION_GUARD_FIX)
            conn.execute(MIGRATION_CONTENT_GUARD)
        yield pool
    finally:
        pool.close()
        with psycopg.connect(url, autocommit=True) as conn:
            conn.execute(f'DROP SCHEMA {schema} CASCADE')


def test_archive_suppression_and_trigger_preserve_discord(db):
    with db.connection() as conn, conn.transaction(), conn.cursor() as cur:
        cur.execute("""INSERT INTO content_links(role_id,url,source_kind,source_message_id,root_message_id)
                        VALUES ('r','https://imgur.com/abcde','root','discord-1','discord-1')""")
        cur.execute("""INSERT INTO content_links(role_id,url,goyangi_content_id,goyangi_set_id,source_kind)
                        VALUES ('r','https://cdn.goyangi.pics/v1/a/b/clip.webp','clip','set-1','goyangi')""")
        assert content_dedup.remove_set(cur, 'set-1', 'discord-1', {'kind':'user-confirmed-pair'}) == 1
    with db.connection() as conn:
        assert conn.execute("SELECT count(*) FROM content_links WHERE source_kind='goyangi'").fetchone()[0] == 0
        assert conn.execute("SELECT count(*) FROM content_links WHERE source_kind='root'").fetchone()[0] == 1
        assert conn.execute('SELECT count(*) FROM goyangi_duplicate_archive').fetchone()[0] == 1
        assert conn.execute("""INSERT INTO content_links(role_id,url,goyangi_set_id,source_kind)
                           VALUES ('r','https://cdn.goyangi.pics/v1/a/b/again.webp','set-1','goyangi')
                           RETURNING content_link_id""").fetchone() is None


def test_incomplete_database_set_is_queued_for_full_verification(db):
    with db.connection() as conn, conn.transaction(), conn.cursor() as cur:
        cur.execute("""INSERT INTO content_links(role_id,url,goyangi_content_id,goyangi_set_id,source_kind)
                        VALUES ('r','https://cdn.goyangi.pics/v1/a/b/clip.webp','clip','set-2','goyangi')""")
        cur.execute("""INSERT INTO content_links(role_id,url,source_kind,source_message_id,root_message_id)
                        VALUES ('r','https://goyangi.pics/v/clip.webp','root','discord-2','discord-2')""")
        cur.execute(content_dedup.LOCK_SQL)
        assert content_dedup.reconcile_exact(cur, roots={'discord-2'}) == 0
    with db.connection() as conn:
        assert conn.execute('SELECT count(*) FROM content_links').fetchone()[0] == 2
        assert conn.execute('SELECT count(*) FROM goyangi_duplicate_sets WHERE set_id=%s', ('set-2',)).fetchone()[0] == 0
        queued = conn.execute(
            'SELECT payload, reason FROM goyangi_pending_sets WHERE set_id=%s', ('set-2',)
        ).fetchone()
        assert queued[0]['existing_only'] is True
        reason = queued[1].decode() if isinstance(queued[1], bytes) else queued[1]
        assert reason == 'Discord post candidate'


def test_confirmed_clip_archive_keeps_rest_of_set_and_blocks_reingest(db):
    with db.connection() as conn, conn.transaction(), conn.cursor() as cur:
        cur.execute("""INSERT INTO content_links(role_id,url,source_kind,source_message_id,root_message_id)
                        VALUES ('r','https://imgur.com/a/album123','root','discord-3','discord-3')""")
        cur.execute("""INSERT INTO content_links(role_id,url,goyangi_content_id,goyangi_set_id,source_kind)
                        VALUES ('r','https://cdn.goyangi.pics/v1/a/b/duplicate.webp','duplicate','set-3','goyangi'),
                               ('r','https://cdn.goyangi.pics/v1/a/b/unique.webp','unique','set-3','goyangi')""")
        cur.execute(content_dedup.LOCK_SQL)
        assert content_dedup.remove_content(
            cur, 'duplicate', 'r', 'set-3', 'discord-3', {'kind': 'user-confirmed-content'}
        ) == 1
        assert content_dedup.remove_content(
            cur, 'future-duplicate', 'r', 'set-3', 'discord-3', {'kind': 'video-fingerprint-v1'}
        ) == 0

    with db.connection() as conn:
        assert conn.execute(
            "SELECT goyangi_content_id FROM content_links WHERE source_kind='goyangi' ORDER BY goyangi_content_id"
        ).fetchall() == [('unique',)]
        assert conn.execute("SELECT count(*) FROM goyangi_duplicate_archive").fetchone()[0] == 1
        assert conn.execute(
            "SELECT count(*) FROM goyangi_duplicate_contents WHERE content_id='duplicate' AND role_id='r'"
        ).fetchone()[0] == 1
        assert ('future-duplicate', 'r') in content_dedup.blocked_contents(conn.cursor())
        assert conn.execute(
            """INSERT INTO content_links(role_id,url,goyangi_content_id,goyangi_set_id,source_kind)
               VALUES ('r','https://cdn.goyangi.pics/v1/a/b/reingested.webp','duplicate','set-3','goyangi')
               RETURNING content_link_id"""
        ).fetchone() is None
        assert conn.execute(
            """INSERT INTO content_links(role_id,url,goyangi_content_id,goyangi_set_id,source_kind)
               VALUES ('r','https://cdn.goyangi.pics/v1/a/b/another.webp','another','set-3','goyangi')
               RETURNING content_link_id"""
        ).fetchone() is not None
        assert conn.execute(
            """INSERT INTO content_links(role_id,url,goyangi_content_id,goyangi_set_id,source_kind)
               VALUES ('r','https://cdn.goyangi.pics/v1/a/b/future.webp','future-duplicate','set-3','goyangi')
               RETURNING content_link_id"""
        ).fetchone() is None
